#!/usr/bin/env bash
# install Nginx 

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx and restart it
sudo nginx -t
sudo service nginx start


